MediaQuery: Rewrite
Nitech-Festival-Executive-Committee/koudaisai pull request #106
Opened 2024-10-07 06:24 UTC by ViniciusBrJp

Closes [メディアクエリの書き方を統一](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/86)

## 概要

メディアクエリの書き方を統一した

## 変更内容

変更前：
`@import "variables";

.canvas {
  position: relative;
  z-index: -100;
  display: flex;
  justify-content: center;
  transition: 1s;
}
.canvasBackground {
  z-index: -100;
  width: 100vw;
  height: calc(100vh - var(--main-padding-top));
  object-fit: cover;
}
.canvasImg {
  --max-height: 60vh;
  position: absolute;
  top: 52%;
  left: 50%;
  width: 95vw;
  max-height: var(--max-height);
  object-fit: contain;
  transform: translate(-50%, -50%);
}

@include phone {
  .canvasBackground {
    width: 100vw;
  }

  .canvasImg {
    --max-height: 50vh;
    width: 100vw;
  }
}
`
変更後
`@import "variables";

.canvas {
  position: relative;
  z-index: -100;
  display: flex;
  justify-content: center;
  transition: 1s;
}
.canvasBackground {
  z-index: -100;
  width: 100vw;
  height: calc(100vh - var(--main-padding-top));
  object-fit: cover;
  @include phone {
    width: 100vw;
  }
}
.canvasImg {
  --max-height: 60vh;
  position: absolute;
  top: 52%;
  left: 50%;
  width: 95vw;
  max-height: var(--max-height);
  object-fit: contain;
  transform: translate(-50%, -50%);
  @include phone {
    width: 100vw;
  }
}
`

## 確認方法

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- [ ] 機密情報が含まれていないことを確認した(含まれている場合は直ちにリモートからコミットを削除すること)
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-07 11:23 UTC, MurakawaTakuya requested changes
修正してfixupお願いします
PR名なんかわかりやすい名前に変えてくれると助かります

2024-10-07 11:23 UTC, MurakawaTakuya commented on src/components/Content/ContentImage/ContentImage.module.scss
>    }
これimgの中じゃないかな?

2024-10-07 11:23 UTC, MurakawaTakuya commented on src/components/Header/HamburgerIcon/HamburgerIcon.module.scss
> +  }
```css
@include phone {
  .hamburgerIconContainer {
    display: flex;
  }
}
```
消し忘れてるのでお願いします

2024-10-07 11:23 UTC, MurakawaTakuya commented on src/components/Header/NavigationButton/NavigationItem.module.scss
>    }
ここの当て方が間違ってるけど、もう使ってないらしいから消して～

2024-10-07 11:23 UTC, MurakawaTakuya commented on src/components/Project/ProjectTag/ProjectTag.module.scss
> +  }
```css
.projectTag {
  span {
  }
}
```
これは消し忘れなので、消してもらって

```css
.project {
  &Tag {
  }
}
```
この中に
```css
@include phone {
  margin: 20px 4px 0;
}
```
をいれてほしいです

2024-10-08 04:50 UTC, MurakawaTakuya approved these changes
LGTM!

2024-10-09 17:08 UTC, senntou approved these changes
OKです！！

2024-10-12 10:52 UTC, merged