jswiper実装
Nitech-Festival-Executive-Committee/koudaisai pull request #114
Opened 2024-10-09 02:56 UTC by senntou

Closes [swiper移行 #13
](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/13)

## 概要

swiper.jsがReactをサポートしているためそれを用いて実装。

navigation button（Swiperを操作する左右のボタン）について、Swiperのデフォルトのものを使うと、特定の条件下でスライドがジャンプ（隣に移動したいのに、別のスライドへ飛ぶ）するバグが発生。
対処法として、Navigation Buttonを別のコンポーネントにして自作した。（SwiperPrev & SwiperNext）

## TODO
- タイトルの横線調整
- タイトルを可変に

## 変更内容

- Swiper実装
- SwiperのCSSを移行
- 左右の影（白いやつ）の位置調整
- タイトル（PICK UP）追加

## 確認方法

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- [ ] 機密情報が含まれていないことを確認した(含まれている場合は直ちにリモートからコミットを削除すること)
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-10 02:46 UTC, senntou commented on src/components/Swiper/Card.tsx
> +}
ここだいぶ気持ち悪いけど、後でSwiperのスライドにタグつけたり、ProjectのObjectに繋げたりは別Issueでやるはずなので一旦無視してくれると嬉しい

2024-10-10 02:46 UTC, senntou commented on src/components/Swiper/CustomSwiper.module.scss
> +      }
この辺も今はいらないけど61stから移したやつです。
後で使うかもなんで一旦残します。

2024-10-10 08:49 UTC, MurakawaTakuya requested changes

2024-10-12 06:09 UTC, senntou commented on src/components/Swiper/CustomSwiper.module.scss
> +      }
縦長画面の時に作用するように変更しました。
これがないと、タブレットで見ているときの表示が崩れる。

2024-10-12 06:09 UTC, senntou commented on src/components/Swiper/SwiperButtons/SwiperButtons.module.scss
> +  }
こっちも縦長画面では表示しないよう変更

2024-10-12 11:29 UTC, MurakawaTakuya approved these changes
めっちゃいいね、LGTM!

2024-10-13 09:27 UTC, ViniciusBrJp commented on src/components/Swiper/CustomSwiper.tsx
> +        </SwiperSlide>
このタクヤのやつは大丈夫？

2024-10-13 09:39 UTC, MurakawaTakuya commented on src/components/Swiper/CustomSwiper.tsx
> +        </SwiperSlide>
変わってたよ～

2024-10-13 09:39 UTC, ViniciusBrJp approved these changes
LGTM!

2024-10-13 09:49 UTC, merged