名工大王ページを作成
Nitech-Festival-Executive-Committee/koudaisai pull request #153
Opened 2024-10-16 06:39 UTC by MurakawaTakuya

Closes [[ふぁんきー。]名工大王企画](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/59)

## 概要

名工大王ページを作成

## 変更内容

- 名工大王ページを作成
- 企画ページのタイトル修正忘れ
- ロゴのサイズを若干小さくした

## 確認方法

`http://localhost:3000/project/mini-game/`

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- [ ] 機密情報が含まれていないことを確認した(含まれている場合は直ちにリモートからコミットを削除すること)
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-16 09:58 UTC, senntou commented
`http://localhost:3000/project/mini-game/`
確認方法にこう書いてあるけど、
`http://localhost:3000/project/nitech-king/`
多分こっちですね

2024-10-16 10:00 UTC, senntou requested changes
これだけお願いします～

2024-10-16 10:00 UTC, senntou commented on src/app/project/nitech-king/nitechKing.tsx
> +          また、シートの半券を投票箱に投票することで名工大王の予想に参加できます。,
なんか`，`が入ってる

![image](https://github.com/user-attachments/assets/f2f54afe-79b7-46bb-bcc8-b342a9acdc4e)

2024-10-16 10:03 UTC, MurakawaTakuya commented on src/app/project/nitech-king/nitechKing.tsx
> +          また、シートの半券を投票箱に投票することで名工大王の予想に参加できます。,
確認お願い～
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/153/commits/eb5a9bdd1f6a06c20507662dc14802074562f2be

2024-10-16 10:04 UTC, senntou approved these changes
修正ありがとぅ
LGTMですぅ

2024-10-16 13:45 UTC, ViniciusBrJp commented on src/app/project/nitech-king/nitechKing.tsx
> +          2代目名工大王の予想で景品ゲットのチャンス!
結構好みの違いになりますが、!と?は全角の方が見た目がいいと思います

2024-10-16 13:46 UTC, ViniciusBrJp approved these changes
LGTM

2024-10-19 16:05 UTC, kazumJ05 reviewed
LGTMです、ビラ(もしくは手持ち看板)待ち

2024-10-23 11:22 UTC, MurakawaTakuya commented
https://koudaisai.onamaeweb.jp/project/nitech-king

2024-10-28 07:36 UTC, merged