お化け屋敷Web作成
Nitech-Festival-Executive-Committee/koudaisai pull request #156
Opened 2024-10-16 10:52 UTC by kazumJ05

Closes [お化け屋敷](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/66)

## 概要

お化け屋敷のWebページを作成
企画タグが不足

## 変更内容

- お化け屋敷のwebページを作成
## 確認方法

`http://localhost:3000/project/haunted-house/`

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- [ ] 機密情報が含まれていないことを確認した(含まれている場合は直ちにリモートからコミットを削除すること)
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-17 06:43 UTC, MurakawaTakuya requested changes
命名規則の統一にご協力を～
参考: https://discord.com/channels/1286538073177329695/1286546126392004678/1296358705616523264

2024-10-17 06:43 UTC, MurakawaTakuya commented on src/app/project/haunted-house/haunted-house.tsx
> +export const hauntedHouseProjectData: ProjectData = {
命名規則の統一(ファイル名も)

2024-10-17 06:43 UTC, MurakawaTakuya commented on src/app/project/haunted-house/page.tsx
> +export default function ProjectHauntedHouse() {
命名規則の統一

2024-10-19 17:08 UTC, MurakawaTakuya reviewed
修正お願いしますー

2024-10-19 17:08 UTC, MurakawaTakuya commented on src/app/project/haunted-house/hauntedHouse.tsx
> +  category: [CATEGORY.STUDENT],
IMO
`CATEGORY.FAMILY,CATEGORY.EXPERIENCE,`もあってもいいのかな～とおもいました

2024-10-19 17:08 UTC, MurakawaTakuya commented on src/app/project/haunted-house/hauntedHouse.tsx
> +};
ここの指定方法が変わったので確認お願いします
[createDateの引数をobjectに変更](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/161)

手順
```
git switch main
git fetch
git pull origin main
git switch text/66-haunted-house
git rebase main
色々修正してコミット
git push --force-with-lease origin text/66-haunted-house
```

2024-10-20 01:48 UTC, kazumJ05 commented on src/app/project/haunted-house/hauntedHouse.tsx
> +  category: [CATEGORY.STUDENT],
カテゴリーはとりあえずで1つだけつけてましたが、自分でも確認して付与しました。追加するならたしかに`CATEGORY.FAMILY, CATEGORY.EXPERIENCE`の2つだと思います

2024-10-20 01:48 UTC, kazumJ05 commented on src/app/project/haunted-house/hauntedHouse.tsx
> +};
修正しました

2024-10-20 04:05 UTC, MurakawaTakuya approved these changes
LGTMです、全部揃ってると思うのでよければOpenにしてから、Projectの方でissueを申請者確認中の方に移動していただけると助かります

そういえば後で時間があったらダークモード実装します(多分そんな時間はかからないと思ってる)

2024-10-20 05:14 UTC, senntou approved these changes
LGTMです～！

2024-10-21 04:42 UTC, MurakawaTakuya commented
[テスト環境デプロイ #215](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/215)
テスト環境: https://koudaisai.onamaeweb.jp/project/haunted-house/

2024-10-24 07:09 UTC, senntou requested changes
scssファイルが`haunted-house.scss`になっているのはキャメルケースに直してもらったほうが良いかも。

あとはこのPRも企画ページ以外の変更を含んでいるので、他のPRとコンフリクトしないかを十分に注意してほしい。
コンフリクトする可能性があるなら、ContentBoxとかContentTitleの変更は別PRにして、先にmainにマージするほうが良いと思います。

2024-10-24 07:09 UTC, senntou commented on src/app/project/haunted-house/haunted-house.scss
> +}
これでも問題ないけど、scssの`:global`を使う書き方とかが俺は好きかも？

例えば、
```
.hauntedPage {
  :global {
    .contentTitle {
      /* hoge */
    }
  }
}
```
これだと、hauntedPage自体はCSS Moduleの恩恵を受けられるから、.contentBoxに当てるCSSのスコープが小さくなる。

2024-10-24 07:09 UTC, senntou commented on src/app/project/haunted-house/haunted-house.scss
> +}
`src/components/Swiper/CustomSwiper.module.scss`で俺が使ってる漢字と一緒かな

2024-10-29 07:39 UTC, MurakawaTakuya commented
[ダークモード実装](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/203)は別PRで作成することにしました

2024-10-30 07:01 UTC, senntou approved these changes
LGTMです！！！

2024-10-30 07:02 UTC, merged