コミュニティーストリートページを追加
Nitech-Festival-Executive-Committee/koudaisai pull request #160
Opened 2024-10-17 01:37 UTC by senntou

Closes [ [青天の霹靂]コミュニティーストリート #71 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/71)

## 概要

カテゴリータグは一旦展示だけ付けました。（家族向け、学生向け等必要か？未確認？）
ビラ、ロゴともにTODOです。

## 変更内容

## 確認方法

http://localhost:3000/project/community-street

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- [ ] 機密情報が含まれていないことを確認した(含まれている場合は直ちにリモートからコミットを削除すること)
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-17 06:42 UTC, MurakawaTakuya requested changes
命名規則の統一にご協力を～
参考: https://discord.com/channels/1286538073177329695/1286546126392004678/1296358705616523264

2024-10-17 06:42 UTC, MurakawaTakuya commented on src/app/project/community-street/communityStreetData.tsx
> +export const communityStreetData: ProjectData = {
命名規則の統一、ファイル名も

2024-10-17 06:42 UTC, MurakawaTakuya commented on src/app/project/community-street/page.tsx
> +export default function CommunityStreetPage() {
命名規則の統一

2024-10-19 15:37 UTC, kazumJ05 reviewed
「企画特有の内容」の部分を反映できると企画の内容を少し増やせると思いました

2024-10-19 16:34 UTC, senntou commented
> (間違っていたらすみません) communityStreetData.tsxのファイル名の"Data"の部分は無くなったと思います
ファイル名だけ直せてませんでした...。

企画特有の内容はこんな形で追加しましたがどうでしょうか？
タイトル微妙だったらまた変えます。

![image](https://github.com/user-attachments/assets/9adb0f29-e862-419c-be13-58f4e5c06cce)

2024-10-20 01:32 UTC, kazumJ05 commented
> > (間違っていたらすみません) communityStreetData.tsxのファイル名の"Data"の部分は無くなったと思います
> > ファイル名だけ直せてませんでした...。
> 
> 企画特有の内容はこんな形で追加しましたがどうでしょうか？ タイトル微妙だったらまた変えます。
> 
> ![image](https://private-user-images.githubusercontent.com/82887636/378105523-9adb0f29-e862-419c-be13-58f4e5c06cce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzODgxNzQsIm5iZiI6MTcyOTM4Nzg3NCwicGF0aCI6Ii84Mjg4NzYzNi8zNzgxMDU1MjMtOWFkYjBmMjktZTg2Mi00MTljLWJlMTMtNThmNGU1YzA2Y2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDAxMzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYzMxZDM0MjE5NmMxODI5YzgyNTExODA5MTc2OWNjYzUzM2QzZTU3ODg4NDkwZTFhZmVkZTQzOTFkYmM3Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TzKQQFVxwEqdqBZJgRqA3vGgtq-nDHTg7AtPvkP41JI)

ありがとうございます、記載するならこの表記しかないかなと思います。

2024-10-20 01:33 UTC, kazumJ05 reviewed
LGTMです、ロゴ・ビラ待ち

2024-10-20 06:08 UTC, senntou commented
ビラロゴ追加・カテゴリー追加しました～

2024-10-20 09:33 UTC, MurakawaTakuya requested changes

2024-10-20 09:33 UTC, MurakawaTakuya commented on src/app/project/community-street/page.tsx
> +  return <Project projectData={communityStreet} />;
タイトルが長いのでスマホ表示の時にはみ出している
Projectコンポーネントのpropsで`projectTitleSize`をつけるとhのサイズを指定できるので小さくして欲しい
![image](https://github.com/user-attachments/assets/226dead4-a1ac-4117-ba28-158d4d2a313c)

2024-10-20 09:38 UTC, senntou commented
@MurakawaTakuya 
修正した。
PCだと若干タイトル小さくなるけどよろしいか？
![image](https://github.com/user-attachments/assets/fedcec1c-50f7-4d70-9e3a-83894e6e672b)

2024-10-20 09:40 UTC, MurakawaTakuya commented
@senntou 
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/160#issuecomment-2424782000
大丈夫!逆にロゴがでかすぎたからfixup入れておきました

2024-10-20 09:42 UTC, MurakawaTakuya approved these changes
一旦approve出しておきます、LGTM!

2024-10-20 09:42 UTC, MurakawaTakuya commented on src/app/project/community-street/communityStreet.tsx
> +// TODO: swiper-slideにスライドを追加
コレは解決してる?

2024-10-20 09:44 UTC, senntou commented on src/app/project/community-street/communityStreet.tsx
> +// TODO: swiper-slideにスライドを追加
解決してないけど、別PRになる。
他のやつではここに書いてないし、書かなくてもよいかも（）

2024-10-20 11:44 UTC, kazumJ05 approved these changes
LGTMです

2024-10-21 04:43 UTC, MurakawaTakuya commented
[テスト環境デプロイ #215](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/215)
テスト環境: https://koudaisai.onamaeweb.jp/project/community-street

2024-10-25 14:47 UTC, merged