[さくらんボーイ]VSディーラー
Nitech-Festival-Executive-Committee/koudaisai pull request #175
Opened 2024-10-17 15:39 UTC by senntou

Closes [ [さくらんボーイ]VSディーラー #68 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/68)

## 概要

VSディーラーページ実装

## 変更内容

## 確認方法

http://localhost:3000/project/vs-dealer

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- [ ] 機密情報が含まれていないことを確認した(含まれている場合は直ちにリモートからコミットを削除すること)
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-19 15:28 UTC, kazumJ05 commented on src/app/project/vs-dealer/vsDealer.tsx
> +const schedule = {
日付タグが2日目しか表示されていないです
<img width="365" alt="スクリーンショット 2024-10-20 午前0 25 17" src="https://github.com/user-attachments/assets/31836f09-1424-46a1-8572-6c112adf29ed">

2024-10-19 15:28 UTC, kazumJ05 commented on src/app/project/vs-dealer/vsDealer.tsx
> +          11月16日(土) 10:00～、10:30～、11:30～、12:30～、13:30～、14:30～
16日も17日と同様の開催時間なので変更お願いします

2024-10-19 16:28 UTC, senntou commented
@kazumJ05 
ありがとうございます！
修正しました！

2024-10-19 17:10 UTC, MurakawaTakuya commented on src/app/project/vs-dealer/vsDealer.tsx
> +  category: [],
```
    CATEGORY.STAGE_PROJECT,
    CATEGORY.STUDENT,
    CATEGORY.EXPERIENCE,
```
たぶんこの辺のタグを適当につけておいてもらえると～

2024-10-19 17:18 UTC, senntou commented on src/app/project/vs-dealer/vsDealer.tsx
> +  category: [],
これってステージ企画なの...？

2024-10-19 17:25 UTC, MurakawaTakuya commented on src/app/project/vs-dealer/vsDealer.tsx
> +  category: [],
違いますね(違う(ちゃうね))

2024-10-19 17:35 UTC, senntou commented
@MurakawaTakuya 
タグ付けました～

2024-10-20 01:25 UTC, kazumJ05 commented
> @kazumJ05 ありがとうございます！ 修正しました！

確認しました、ありがとうございます

2024-10-20 05:12 UTC, kazumJ05 reviewed
LGTMです、ロゴ・ビラ待ち(書き出しましたので更新お願いします)

2024-10-20 05:57 UTC, senntou commented
ロゴビラ追加しました

2024-10-20 06:02 UTC, MurakawaTakuya commented on src/app/project/vs-dealer/vsDealer.tsx
> +      ),
```suggestion
      content: "企画局 iori.nomoto@koudaisai.com"
```
ごめん取りこぼしてた
これ以外はOKです

2024-10-20 09:35 UTC, senntou commented
@MurakawaTakuya 
修正した。
画像と開催日程が違うのが若干...

2024-10-20 09:37 UTC, MurakawaTakuya commented on src/app/project/vs-dealer/vsDealer.tsx
> +  },
@senntou 
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/175#issuecomment-2424775992
たしかにそうだね、じゃあここに日程も合わせる?(ここは合わせたほうが良い気もする)

2024-10-20 09:42 UTC, senntou commented
@MurakawaTakuya 
修正した、それに伴ってswiperOptionもいらなそうなので消している

2024-10-20 09:45 UTC, MurakawaTakuya approved these changes
LGTMです、時間が微妙にずれてる問題は担当者に確認します

> TODO: 下記PRをmainにマージ
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/174

これだけもしまだだったらよろしく

2024-10-20 09:47 UTC, MurakawaTakuya requested changes
このタグついてないわ、確認お願い
> 予約制(チケット制)

https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/68#issuecomment-2413340796

2024-10-20 10:34 UTC, senntou commented
分かりやすいようにmainの変更取り込んで一回force push入れました、こっから修正またします

2024-10-20 10:37 UTC, senntou commented
予約タグ追加しました

2024-10-20 10:38 UTC, MurakawaTakuya approved these changes
LGTM!

2024-10-20 10:39 UTC, MurakawaTakuya commented
ビラの時間が間違ってるらしい、今は一旦このままで、マジまでに間に合えば入れ替えましょう

2024-10-20 11:43 UTC, kazumJ05 approved these changes
LGTMです

2024-10-21 04:44 UTC, MurakawaTakuya commented
[テスト環境デプロイ #215](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/215)
テスト環境: https://koudaisai.onamaeweb.jp/project/vs-dealer

2024-10-24 01:17 UTC, merged