ステージ企画sparkページ作成
Nitech-Festival-Executive-Committee/koudaisai pull request #176
Opened 2024-10-17 15:52 UTC by senntou

Closes [ [ぽちゃっこ]学生ステージ企画 #58 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/58)

## 概要

## 変更内容

## 確認方法

http;//localhost:3000/project/spark

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- [ ] 機密情報が含まれていないことを確認した(含まれている場合は直ちにリモートからコミットを削除すること)
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-19 15:46 UTC, kazumJ05 reviewed
12. その他掲載必須事項の内容をどこかに反映させてほしいです(1行目だけで大丈夫です)
あと出演団体などの情報を反映させてほしいです

2024-10-19 15:46 UTC, kazumJ05 commented on src/app/project/spark/spark.tsx
> +    startDate: createDate({
昨日Web申請が更新されて日時が変更されていたので、対応お願いします

2024-10-19 17:07 UTC, senntou commented
@kazumJ05 
指摘されていた点を修正しました！
お願いします。

2024-10-20 01:22 UTC, kazumJ05 commented
> @kazumJ05 指摘されていた点を修正しました！ お願いします。

確認しました、ありがとうございます

2024-10-20 01:22 UTC, kazumJ05 approved these changes
LGTMです
(ごめんなさいビラ待ちだったけど間違えてapproveしちゃいました)

2024-10-20 05:34 UTC, MurakawaTakuya reviewed
テーブルもしっかりできてて最高です、LGTM!
もし余力があれば
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/blob/f0ffd9e7a23682526f4c07fdbeca98623969743a/src/components/Content/ContentBox/ContentBox.module.scss#L41
これにolも追加してほしいかなと思った、無理そうだったらissue立ててくれればこっちでやります

一応リンクだけしときます
ref: [企画ページのお問合せ先を消す](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/208)

2024-10-20 05:34 UTC, MurakawaTakuya commented on src/app/project/spark/spark.tsx
> +        </p>
これも上同様ol>li表記でいいんじゃないかなと思った、まかせます

2024-10-20 10:27 UTC, senntou commented
@MurakawaTakuya 
olのstyle追加、それに伴うページの変更入れました

見た目変えてるので確認を！

2024-10-20 10:29 UTC, MurakawaTakuya commented
@senntou 
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/176#issuecomment-2424826300
良いと思う!
結局こっちはこのままいく?
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/176#discussion_r1807650269

2024-10-20 10:39 UTC, senntou commented
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/176#issuecomment-2424827166
おれはそれで良いと思ってるけど、変えた方が良いなら変えます！

2024-10-20 10:40 UTC, MurakawaTakuya reviewed
それならLGTMです、ビラ待ちですかね
ビラ来たらapprove出します

2024-10-20 16:01 UTC, MurakawaTakuya commented
これビラないらしいわ、LGTM!

2024-10-20 16:01 UTC, MurakawaTakuya approved these changes
これビラないらしいわ、LGTM!

2024-10-20 16:03 UTC, MurakawaTakuya requested changes

2024-10-20 16:03 UTC, MurakawaTakuya commented on src/app/project/spark/page.tsx
> +    <Project projectData={spark}>
```suggestion
    <Project projectData={spark} brochurePath={""}>
```
ごめん一箇所だけ
rebaseしてこれだけ追加してください

2024-10-21 05:26 UTC, MurakawaTakuya approved these changes
修正しときました、LGTM!

2024-10-21 05:43 UTC, MurakawaTakuya commented
[テスト環境デプロイ #215](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/215)
テスト環境: https://koudaisai.onamaeweb.jp/project/spark

2024-10-28 07:34 UTC, MurakawaTakuya commented
修正待ち
[複数列を含むProjectTableを修正](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/227)

2024-10-28 07:38 UTC, merged