[らヴりん]VRコースター
Nitech-Festival-Executive-Committee/koudaisai pull request #177
Opened 2024-10-17 16:10 UTC by senntou

Closes [ [らヴりん]VRコースター #61 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/61)

## 概要

## 変更内容

TODO ビラ

## 確認方法

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- [ ] 機密情報が含まれていないことを確認した(含まれている場合は直ちにリモートからコミットを削除すること)
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-19 15:23 UTC, kazumJ05 reviewed
LGTMです、ビラ待ち

2024-10-19 17:10 UTC, senntou commented
TODO:
> (開催場所の欄にマップのリンクを載せてください)

2024-10-20 05:22 UTC, MurakawaTakuya requested changes
独裁国家なのでタグを指定された以外で追加・改変しても問題ないです
異論はもしたくが受け止めます

2024-10-20 05:22 UTC, MurakawaTakuya commented on src/app/project/vr-coaster/vrCoaster.tsx
> +    },
```suggestion
    {
      title: "お問い合わせ先",
      content: "企画局 rito.saiki@koudaisai.com",
    },
```
申請の書き方がちょっと違ったけどこれでお願いします

(まあ後で消えるかもだけど)

2024-10-20 05:22 UTC, MurakawaTakuya commented on src/app/project/vr-coaster/vrCoaster.tsx
> +  category: [CATEGORY.STUDENT, CATEGORY.EXPERIENCE],
IMO
CATEGORY.FAMILY「ママ、僕もVRやってみたいな」

2024-10-20 05:22 UTC, MurakawaTakuya commented on src/app/project/vr-coaster/vrCoaster.tsx
> +        </p>
```suggestion
        <p>
          迫力満点のVRコースターに乗ってみませんか⁈仮想現実の世界でスリル満点の体験を、リアルな動きと共に楽しめます！
          <br />
          手作りの木製カートに乗り込み、心臓が高鳴るジェットコースターの世界をお楽しみください‼
        </p>
```
IMO
若干読みにくいから改行ほしいです

2024-10-20 05:43 UTC, senntou commented
@MurakawaTakuya 
修正しました～

お問合せはどうせ消すから良いだろうが！！！の気持ちだった（）

2024-10-20 05:44 UTC, MurakawaTakuya commented
@senntou 
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/177#issuecomment-2424613402
どのタイミングで消すかわからんから一応ねw
もしかしたら公開後かもしれないからね

2024-10-20 05:47 UTC, MurakawaTakuya reviewed
LGTM!

2024-10-20 09:50 UTC, senntou commented
@MurakawaTakuya 
@kazumJ05 
ビラ追加できたので問題なければApproveお願いします！！

2024-10-20 09:55 UTC, MurakawaTakuya approved these changes
LGTM!

2024-10-20 10:14 UTC, kazumJ05 approved these changes
LGTMです

2024-10-21 04:45 UTC, MurakawaTakuya commented
[テスト環境デプロイ #215](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/215)
テスト環境: https://koudaisai.onamaeweb.jp/project/vr-coaster

2024-10-24 01:17 UTC, merged