Text/60 kouya
Nitech-Festival-Executive-Committee/koudaisai pull request #193
Opened 2024-10-18 12:43 UTC by nqmery

Closes [ [ショコラ]後夜祭 #60 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/60)

## 概要

## 変更内容

- 変更1
  - 説明が必要なら記述
- 変更2

## 確認方法

http://localhost:3000/project/excursion-riddles/

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- [ ] 機密情報が含まれていないことを確認した(含まれている場合は直ちにリモートからコミットを削除すること)
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-19 14:50 UTC, kazumJ05 commented on src/app/project/kouya/kouya.tsx
> +  day1: {
2日目なのでday2でお願いします

2024-10-19 14:50 UTC, kazumJ05 commented on src/app/project/kouya/kouya.tsx
> +          <Underline>
文章が長くて下にのみ線が引かれているので、各行ごとに線を引いたほうがきれいかなと思いました
<img width="357" alt="スクリーンショット 2024-10-19 午後11 49 01" src="https://github.com/user-attachments/assets/9fb2dbcb-6290-40fa-a790-f66279d4a0fd">

2024-10-19 15:21 UTC, MurakawaTakuya reviewed
フォーマッタで差分が出たのでfixupで入れておきました
ついでに変更した指摘とロゴも含めました(指摘部分はよく読んでね)
次変更をいれる前にはpullを忘れずに

2024-10-19 15:21 UTC, MurakawaTakuya commented on src/app/project/kouya/kouya.tsx
> +    },
消してOKです

2024-10-19 15:21 UTC, MurakawaTakuya commented on src/app/project/kouya/kouya.tsx
> +          <p>ダンスを行う際は周りと十分に距離をとり、怪我をしないようご注意ください。</p>
```suggestion
        "ダンスを行う際は周りと十分に距離をとり、怪我をしないようご注意ください。",
```

IMO
テキストだけならこっちでもOK、特に問題があるわけではないので面倒であればこのままでもいいです

2024-10-19 15:21 UTC, MurakawaTakuya commented on src/app/project/kouya/kouya.tsx
> +      minute: 0o0,
謎顔文字じゃなくて0でOKですw

2024-10-19 15:22 UTC, MurakawaTakuya commented
ビラが不足

2024-10-20 08:56 UTC, MurakawaTakuya requested changes

2024-10-20 08:56 UTC, MurakawaTakuya commented on src/app/project/kouya/kouya.tsx
> +    }),
終了時間18:10らしい、変更お願い

2024-10-20 15:41 UTC, MurakawaTakuya commented
全部修正突っ込みました

2024-10-20 15:41 UTC, MurakawaTakuya approved these changes
self LGTM!

2024-10-21 00:59 UTC, kazumJ05 approved these changes
LGTMです

2024-10-21 04:46 UTC, MurakawaTakuya commented
[テスト環境デプロイ #215](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/215)
テスト環境: https://koudaisai.onamaeweb.jp/project/kouya/

2024-10-21 04:52 UTC, MurakawaTakuya commented
デプロイしたら
ゴージャス画像が表示されなくなった
パスがおかしそう
`https://koudaisai.onamaeweb.jp/62nd/project/tyuya//62nd/project/tyuya/gorgeous.webp`

2024-10-24 01:17 UTC, merged