[エアドロ]模擬店PR
Nitech-Festival-Executive-Committee/koudaisai pull request #197
Opened 2024-10-18 14:01 UTC by ViniciusBrJp

Closes [[エアドロ]模擬店PR #196](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/196)

## 概要

ロゴ、ビラ以外

## 変更内容

- 変更1
  - 説明が必要なら記述
- 変更2

## 確認方法

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- [ ] 機密情報が含まれていないことを確認した(含まれている場合は直ちにリモートからコミットを削除すること)
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-19 01:01 UTC, kazumJ05 reviewed
LGTMです、ロゴ・ビラ待ち
(この企画はロゴもビラもない可能性があるのでこの部分の表示方法は要相談だと思います)

2024-10-20 04:21 UTC, MurakawaTakuya requested changes

2024-10-20 04:21 UTC, MurakawaTakuya commented on src/app/project/mogiten-PR/mogitenPR.tsx
> +  link: "mogiten-PR", // 複数単語の場合はハイフンつなぎで記述
URLは基本小文字を使用します(大文字小文字は無視されるが、基本小文字に統一する)、余裕があればディレクトリ名含め修正してください
参考: https://www.switchitmaker2.com/web-production/capital-small-letter/
もしかしたらビラ・ロゴの画像が404になる可能性があるので、その時はここを確認してください

2024-10-20 04:21 UTC, MurakawaTakuya commented on src/app/project/mogiten-PR/mogitenPR.tsx
> +const place = " 2号館前ステージ";
不要なスペース削除
```suggestion
const place = "2号館前ステージ";
```

2024-10-20 04:21 UTC, MurakawaTakuya commented on src/app/project/mogiten-PR/mogitenPR.tsx
> +      content: "模擬局　中野貴博　takahiro.nakano@koudaisai.com",
- 本名は載せないでください
- スペースは半角を使ってください
```suggestion
      content: "模擬局 takahiro.nakano@koudaisai.com",
```

2024-10-20 04:25 UTC, MurakawaTakuya commented
http://localhost:3000/project/mogiten-pr/ -> 404
http://localhost:3000/project/mogiten-PR/ -> 200

パスに大文字があると開発環境では区別されてた、修正してほしい(なんかよくわからんバグ引き起こす可能性があるので)
あと、PRの確認方法にローカルのURLを書いてあると親切ですね

2024-10-20 04:26 UTC, MurakawaTakuya requested changes
パスに大文字があると開発環境では区別されてた、修正してほしい(なんかよくわからんバグ引き起こす可能性があるので)
http://localhost:3000/project/mogiten-pr/ -> 404
http://localhost:3000/project/mogiten-PR/ -> 200

あと、PRの確認方法にローカルのURLを書いてあると親切かな

2024-10-28 08:46 UTC, MurakawaTakuya approved these changes
self LGTM

2024-10-28 09:07 UTC, kazumJ05 approved these changes
LGTMです

2024-10-28 09:37 UTC, merged