CSSのメディアクエリを変数化する
Nitech-Festival-Executive-Committee/koudaisai pull request #43
Opened 2024-09-30 09:25 UTC by senntou

Closes [ CSSのメディアクエリを変数化する #31 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/31)

## 概要

sassの機能を使うことで、メディアクエリの記述を変数化し統一したい

## 変更内容

- phone用mixinを追加
- これまでのメディアクエリを変更

## 変更内容の説明

今後メディアクエリを使用する際は
```
@import "variables"
```
を１行目に追加
```
@include phone {
}
```
を使用してメディアクエリをを適用してください。

## 確認方法

スマホ画面にしても、画面の表示が変わっていないことを確認

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-09-30 09:27 UTC, senntou commented on .vscode/settings.json
> +    "editor.defaultFormatter": "esbenp.prettier-vscode",
cssのformat走ってなかったので追加。
もしかしたらまたフォーマットで差分出るかも。ごめん。

2024-09-30 09:27 UTC, senntou commented on src/components/Header/NavigationButton/NavigationDropDown.tsx
> +        initial="closed"
Framer Motionの警告がコンソールに出ていたので修正のため追加。
このPRと関係ないです。ごめんなさい。

2024-09-30 09:29 UTC, MurakawaTakuya commented
information系のファイルで、mediaqueryを移行する変更が乗ってない気がするけど、mainでブランチ切る前に`git pull`してなかったり...?

2024-09-30 15:44 UTC, MurakawaTakuya requested changes
`src\components\Content\ContentTitle\ContentTitle.module.scss`
このファイル忘れてそう

2024-10-01 01:37 UTC, MurakawaTakuya approved these changes
LGTM!

2024-10-01 01:50 UTC, ViniciusBrJp approved these changes
無視してって言われたところ以外はLGTM

2024-10-01 01:54 UTC, merged