pre-festivalのタイトルを修正
Nitech-Festival-Executive-Committee/koudaisai pull request #74
Opened 2024-10-01 04:43 UTC by ViniciusBrJp

Closes [pre-festivalのタイトルを修正 #53](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/53)

## 概要

「過去のページ」のタイトルをsrc\components\Content\ContentTitle\ContentTitle.tsxコンポーネントに変える

## 変更内容

-  preFestivalのタイトルのコンポーネントをContentTitleに変更

## 変更内容の説明

## 確認方法

「過去のページ」を確認

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-01 04:54 UTC, MurakawaTakuya approved these changes
LGTM!

2024-10-01 08:13 UTC, senntou requested changes

2024-10-01 08:13 UTC, senntou commented on src/components/PreviousFestival/PreviousFestival.tsx
> -      >
この辺の使ってないCSSは一応消しといて欲しいかも！

2024-10-01 10:20 UTC, MurakawaTakuya commented
Closes [`bigTitle={true}`を短縮](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/83#issue-2558798101)
ごめんこれだけ修正お願いしたい!

2024-10-02 10:42 UTC, senntou approved these changes
bigTitleとretroshadowも使ってないはずなので、余裕があれば消しておいてほしいです！

内容はLGTM！

2024-10-04 10:59 UTC, merged