sns-floatを移行
Nitech-Festival-Executive-Committee/koudaisai pull request #81
Opened 2024-10-01 08:45 UTC by senntou

Closes [ sns-floatを移行 #11 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/11)

## 概要

コンポーネントを作成して、src\app\layout.tsxのsns-floatのコメントアウト部分に配置する

## 変更内容

- SnsIconの作成
- SnsIconListの作成
- SnsIconListをヘッダーとLayoutに追加

## 変更内容の説明

SnsIconListは同じコンポーネントをヘッダーとLayoutに用いている。
Layoutに用いているものは、propとしてpcOnlyを渡すことでスマホ画面では表示しないようにした。

## 確認方法

- スマホとPCでSNSアイコンが表示されること
- 押したら新規タブが作成されページが遷移すること
- ホバー中にアイコンにアニメーションが付いていること
- （ヘッダーのCSSを変更したため）ヘッダーのアニメーションが壊れていないこと
- ヘッダー（PC画面）の配置に違和感がないこと
- ハンバーガーアイコンの配置に違和感がないこと

# チェックリスト
- [x] File Changedで不要な変更や誤った変更が無いか確認した
- [x] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [x] レビューを頼んだ人にDiscordでお願いした
- UIを変更した場合
  - [x] PCで見た時に表示が崩れていないことを確認した
  - [x] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-01 09:43 UTC, MurakawaTakuya commented
俺もめっちゃ忘れてたけど、UI変えたり機能追加する系はスクショ貼っとこう～
(後から見返した時にどう変わったか確認するのも面倒だと思うので)

|PC|スマホ|
|-|-|
|![image](https://github.com/user-attachments/assets/3c869560-a5c2-4a2e-8a65-00ffdd8b5625)|![image](https://github.com/user-attachments/assets/7bccd23f-ad02-48e6-949b-16aaaa274657)|

2024-10-01 10:00 UTC, MurakawaTakuya requested changes

2024-10-01 10:00 UTC, MurakawaTakuya commented on src/components/Header/Header.module.scss
> +  width: 100vw;
100vw(中身で横幅いっぱい)にした影響で、スクロールしてmarginが付与された時に100vw + marginになってしまうので、画面に収まりきらない

|device|main|このブランチ|
|-|-|-|
|PC|![image](https://github.com/user-attachments/assets/bad6b261-aa4f-4962-8da2-21112282c859)|![image](https://github.com/user-attachments/assets/7f9f3ef8-63c8-4645-80a3-5a5d7f90a778)|
|スマホ|![image](https://github.com/user-attachments/assets/d7098fa1-1525-4f26-8cb9-1e0956154f12)|![image](https://github.com/user-attachments/assets/cd8b93ae-b996-45b1-893d-b0b9604828d9)|

これ消しても普通に動作しそうだったけど、どっかで必要だったりする?

2024-10-01 10:05 UTC, senntou commented on src/components/Header/Header.module.scss
> +  width: 100vw;
いらないです。

2024-10-01 10:07 UTC, MurakawaTakuya approved these changes
LGTM!

2024-10-02 02:02 UTC, ViniciusBrJp submitted a review, later dismissed
SNSから少し外れてしまうけど、ハンバーガーメニューを早押しすると閉じたはずなのに一瞬メニューが空に表示されてしまう
動画は携帯で撮ったからDiscordに送りました

2024-10-03 07:56 UTC, merged