Bootstrapを廃止する
Nitech-Festival-Executive-Committee/koudaisai pull request #88
Opened 2024-10-01 13:02 UTC by senntou

Closes [ Bootstrapを廃止する #35 ](https://github.com/Nitech-Festival-Executive-Committee/koudaisai/issues/35)

## 概要

bootstrapを廃止するため、ヘッダーでbootstrapを使用している箇所をリファクタリングする

## 変更内容

- bootstrapのクラス名を使っている部分の削除
- bootstrapのアンインストール
- CSSの補修

## 変更内容の説明

一部CSSやコードの分かりにくい部分を書き換えているが、メディアクエリの書き換えなどは別issueでやるはずなので、差分が大きくなりすぎないよう不要な部分のリファクタリングは行っていない。

## 確認方法

bootstrapをアンインストールしたことによって、全体にも少しだけ影響が出ている様子なので確認してほしい。

# チェックリスト
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] 対応したissueをProjectの"レビュー中・待機中"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした
- UIを変更した場合
  - [ ] PCで見た時に表示が崩れていないことを確認した
  - [ ] スマホでも正常に表示されることを確認した(大きい画面と小さい画面両方で)
- Web申請対応の場合
  - [ ] Web申請担当者に確認してもらった

2024-10-02 01:29 UTC, senntou commented
以下のブランチにrebaseして実装しているので、これがマージされたらrebase & deployします。
（rebaseの関係で現状差分がちょっと変だけど、後で直せるはず）

sns-floatの実装
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/81

2024-10-02 05:12 UTC, ViniciusBrJp approved these changes
LGTM

2024-10-03 03:22 UTC, MurakawaTakuya commented
rebaseしてからmainの`font-family`につけてた`important`消してフォント正しくなるか確認

2024-10-03 08:24 UTC, senntou commented
> rebaseしてからmainの`font-family`につけてた`important`消してフォント正しくなるか確認

![image](https://github.com/user-attachments/assets/629b1a73-badb-4b0c-8378-b3954b6802ef)

2024-10-03 09:10 UTC, MurakawaTakuya requested changes
下線と少し距離があるみたい
![image](https://github.com/user-attachments/assets/526cbc96-90bc-4269-94b6-0af76ef19b24)

少し文字の位置が上にずれてるかも
![image](https://github.com/user-attachments/assets/7ab289e1-0450-440a-86a5-1980c974d054)

公開版
![image](https://github.com/user-attachments/assets/6b119e32-8bc0-415f-9fa4-28f3f3bd69a0)

bodyの`font-family`の!importantを消すのもお願いします

2024-10-04 03:30 UTC, MurakawaTakuya commented
@senntou 
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/88#pullrequestreview-2345061299

なんか直った、もしかしたらキャッシュかなにかでおかしくなってたのかも

2024-10-04 03:32 UTC, MurakawaTakuya approved these changes
~~問題なさそう、LGTM!~~

2024-10-04 03:36 UTC, MurakawaTakuya requested changes
訂正、直ってなかったからLGTM戻します

2024-10-04 23:16 UTC, senntou commented
@MurakawaTakuya 
一行だけど修正しました。
確認お願いします！

2024-10-06 06:08 UTC, MurakawaTakuya approved these changes
LGTM!

2024-10-06 06:08 UTC, MurakawaTakuya commented
https://github.com/Nitech-Festival-Executive-Committee/koudaisai/pull/88#pullrequestreview-2345061299
直った
![image](https://github.com/user-attachments/assets/8ffec387-5645-43c7-b5f4-d1e04777b119)

2024-10-06 06:14 UTC, merged